# Generated by Django 3.2.7 on 2022-08-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_longer_subscription_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('title',), 'verbose_name': 'newsletter', 'verbose_name_plural': 'newsletters'},
        ),
    ]
