name: Test

on: [push, pull_request]

jobs:
  build:
    name: build (Python 3.8, Django main
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: |
            setup.py
            tox.ini

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox tox-gh-actions djangorestframework

      - name: Tox tests
        run: |
          tox -v
        env:
          DJANGO: main

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          name: Python 3.8
